### ISSUE TITLE
Deprecation warning for Moodle 3.8+

### ISSUE THREAD

**Issue by rlorenzo** [SonicFoundry/Mediasite-Content-Module-for-Moodle#3]
When running Moodle 3.8 I get this warning:

Use of subplugins.php has been deprecated. Please update your '/usr/local/moodle/releases/dev38/local/mediasite_courses' plugin to provide a subplugins.json file instead.

Need to add a subplugin.json file. See https://docs.moodle.org/dev/Subplugins#db.2Fsubplugins.json

**Comment by sofo-davidk** [comment]
Thanks for the message Rex. We've filed MOOD-128 to update the plugin.
