### ISSUE TITLE
blank page when clicking link in activities block

### ISSUE THREAD

**Issue by Marx1st** [SonicFoundry/Mediasite-Content-Module-for-Moodle#4]
In Moodle courses one can add an "activities block" which lists all activity types in that course. Clicking on the activities type link will open a page which only shows the course's activities of that type.
The same is true when Mediasite activities are added in the course.

We've now updated to Moodle 3.9.2+ (from 3.7.x) and did also update all Mediasite plugins. The Mediasite activities link is still present in the "activities block", but clicking it will open a blank page. There are no errors, even when we activate debugging.

**Comment by sofo-davidk** [comment]
Thanks for reaching out for help, I'm sorry I'm not able to help you directly. Please open a case with customer support, use the Mediasite Customer Care Portal (https://support.sonicfoundry.com/) or call 877.783.7987.
